
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
# deps
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Site settings
title: "Lập Trình Thật Kỳ Diệu"
subtitle: "Tiep Phan Blog"
url: "http://www.tiepphan.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/logo.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

# Pagination
# paginate: 1

# Webmaster tools
webmaster_verifications:
  google: Gcn3Y0oBud7gufI1PtszF7DFNgFOifgLRIaZAoLZWWU
  bing:
  alexa:
  yandex:
  
# Social
social:
  name: Tiep Phan
  links:
    - https://twitter.com/_tieppt
    - https://www.facebook.com/pttiep
    - https://github.com/tieppt

pagination:
  enabled: true
  per_page: 5
  collection: 'posts'

# Archives
jekyll-archives:
  enabled: all
  layouts:
    year: year
    month: month
    day: day
    tag: tagx
    category: tagx
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
